import { SidebarNavigation } from "~/components/sidebar";
import { Separator } from "~/components/ui/separator";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen w-full">
      <SidebarNavigation />
      <Separator
        orientation="vertical"
        className="h-screen border-gray-200 bg-border"
      />
      <div className="ml-36 w-[600px] pt-10">{children}</div>
    </div>
  );
}
